### ISSUE TITLE
network monsoon-samples_default not found

### ISSUE THREAD

**Issue by jeremymcjunkin** [monsooncommerce/monsoon-samples#3]
When I make a request to my function, get the following error in the docker log:
`sam_app_1  | docker.errors.NotFound: 404 Client Error: Not Found ("network monsoon-samples_default not found")`

I'm fairly new to docker, and I'm not sure where this network needs to be defined.  I did not find any other references to `monsoon-samples_default` in the codebase.

Here's the full stacktrace:
```
sam_app_1  | 2019-06-17 20:16:04 Exception on /2015-03-31/functions/GetPresignedURLFunction/invocations [POST]
sam_app_1  | Traceback (most recent call last):
sam_app_1  |   File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 261, in _raise_for_status
sam_app_1  |     response.raise_for_status()
sam_app_1  |   File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
sam_app_1  |     raise HTTPError(http_error_msg, response=self)
sam_app_1  | requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.35/networks/monsoon-samples_default
sam_app_1  | 
sam_app_1  | During handling of the above exception, another exception occurred:
sam_app_1  | 
sam_app_1  | Traceback (most recent call last):
sam_app_1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
sam_app_1  |     response = self.full_dispatch_request()
sam_app_1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
sam_app_1  |     rv = self.handle_user_exception(e)
sam_app_1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
sam_app_1  |     reraise(exc_type, exc_value, tb)
sam_app_1  |   File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
sam_app_1  |     raise value
sam_app_1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
sam_app_1  |     rv = self.dispatch_request()
sam_app_1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
sam_app_1  |     return self.view_functions[rule.endpoint](**req.view_args)
sam_app_1  |   File "/usr/local/lib/python3.7/site-packages/samcli/local/lambda_service/local_lambda_invoke_service.py", line 145, in _invoke_request_handler
sam_app_1  |     self.lambda_runner.invoke(function_name, request_data, stdout=stdout_stream_writer, stderr=self.stderr)
sam_app_1  |   File "/usr/local/lib/python3.7/site-packages/samcli/commands/local/lib/local_lambda.py", line 93, in invoke
sam_app_1  |     self.local_runtime.invoke(config, event, debug_context=self.debug_context, stdout=stdout, stderr=stderr)
sam_app_1  |   File "/usr/local/lib/python3.7/site-packages/samcli/local/lambdafn/runtime.py", line 86, in invoke
sam_app_1  |     self._container_manager.run(container)
sam_app_1  |   File "/usr/local/lib/python3.7/site-packages/samcli/local/docker/manager.py", line 96, in run
sam_app_1  |     container.create()
sam_app_1  |   File "/usr/local/lib/python3.7/site-packages/samcli/local/docker/container.py", line 134, in create
sam_app_1  |     network = self.docker_client.networks.get(self.network_id)
sam_app_1  |   File "/usr/local/lib/python3.7/site-packages/docker/models/networks.py", line 180, in get
sam_app_1  |     self.client.api.inspect_network(network_id, *args, **kwargs)
sam_app_1  |   File "/usr/local/lib/python3.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
sam_app_1  |     return f(self, resource_id, *args, **kwargs)
sam_app_1  |   File "/usr/local/lib/python3.7/site-packages/docker/api/network.py", line 212, in inspect_network
sam_app_1  |     return self._result(res, json=True)
sam_app_1  |   File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 267, in _result
sam_app_1  |     self._raise_for_status(response)
sam_app_1  |   File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 263, in _raise_for_status
sam_app_1  |     raise create_api_error_from_http_exception(e)
sam_app_1  |   File "/usr/local/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
sam_app_1  |     raise cls(e, response=response, explanation=explanation)
sam_app_1  | docker.errors.NotFound: 404 Client Error: Not Found ("network monsoon-samples_default not found")
sam_app_1  | 2019-06-17 20:16:04 172.18.0.1 - - [17/Jun/2019 20:16:04] "POST /2015-03-31/functions/GetPresignedURLFunction/invocations HTTP/1.1" 500 -

```

**Comment by jeremymcjunkin** [comment]
So, it appears that the network name is `$PWD-default`.  At what step of https://medium.com/monsoon-engineering/running-aws-sam-in-a-docker-container-2491596672c2 was that created?

**Comment by mandrews** [comment]
@jeremymcjunkin the `monsoon-samples_default` network in the example should be created by `docker-compose` if it does not already exist. What version of `docker`/ `docker-compose` are you using? I tested with "Docker Version 2.0.0.3 (31259)" on "Mac OS X Mojave 10.14.5 (18F132)" and have attached the expected output:

```bash
$ docker -v
Docker version 18.09.2, build 6247962
$ docker-compose --version
docker-compose version 1.23.2, build 1110ad01
$ cd monsoon-samples/docker-sam
$ docker-compose up sam_app

Creating network "monsoon-samples_default" with the default driver
Building sam_app
...

Building sam_app

Step 1/6 : FROM python:alpine
```

Can you provide similar output so that I can help debug the issue you are facing?

**Comment by jeremymcjunkin** [comment]
@mandrews, not sure if you saw my followup comment, but I figured it out. The name of the network is based of the directory name.  I'm not sure why yours starts with `monsoon-samples` and not `docker-sam`.  I have my `docker-compose.yml` file in a folder called `sam` and the network that gets created is named `sam_default`.

**Comment by mandrews** [comment]
@jeremymcjunkin I'm glad you were able to figure it out! FWIW as you pointed out, the  `docker-compose` prefix defaults to  `$PWD`. It is possible to override this via the `COMPOSE_PROJECT_NAME` environment variable. This environment variable is configured by the `.env` file stored in the Git repository:

```bash
% cd monsoon-samples/docker-sam
% cat .env
COMPOSE_PROJECT_NAME='monsoon-samples'
```

**Comment by jeremymcjunkin** [comment]
Awesome, thanks for the info.
